.travis.yml
appveyor.yml
src/Pkcs11Interop.NetStandard/Pkcs11Interop.DotNetCore.Tests/Pkcs11Interop.DotNetCore.Tests.csproj
src/Pkcs11Interop.NetStandard/Pkcs11Interop/Pkcs11Interop.csproj

Configure CI for Linux and OSX

---

src/Pkcs11Interop/Pkcs11Interop/HighLevelAPI/ISession.cs
src/Pkcs11Interop/Pkcs11Interop/HighLevelAPI40/Session.cs
src/Pkcs11Interop/Pkcs11Interop/HighLevelAPI41/Session.cs
src/Pkcs11Interop/Pkcs11Interop/HighLevelAPI80/Session.cs
src/Pkcs11Interop/Pkcs11Interop/HighLevelAPI81/Session.cs

Signing with context specific signature pin

---

appveyor.yml
build/Pkcs11Interop.nuspec
build/build-all.bat
build/build-nuget.bat
build/build-xamarinmac2.0.bat
build/sign-all.bat
src/Pkcs11Interop.NetStandard/Pkcs11Interop/Pkcs11Interop.csproj
src/Pkcs11Interop/Pkcs11Interop.Mock/LowLevelAPI40/MockDelegates.cs
src/Pkcs11Interop/Pkcs11Interop.Mock/LowLevelAPI41/MockDelegates.cs
src/Pkcs11Interop/Pkcs11Interop.Mock/LowLevelAPI80/MockDelegates.cs
src/Pkcs11Interop/Pkcs11Interop.Mock/LowLevelAPI81/MockDelegates.cs
src/Pkcs11Interop/Pkcs11Interop/Common/NativeMethods.cs
src/Pkcs11Interop/Pkcs11Interop/LowLevelAPI40/Delegates.cs
src/Pkcs11Interop/Pkcs11Interop/LowLevelAPI41/Delegates.cs
src/Pkcs11Interop/Pkcs11Interop/LowLevelAPI80/Delegates.cs
src/Pkcs11Interop/Pkcs11Interop/LowLevelAPI81/Delegates.cs

Xamarin.Mac support

---

appveyor.yml
build/Pkcs11Interop.nuspec
build/build-all.bat
build/build-netstandard2.0.bat
build/build-nuget.bat
build/sign-all.bat
src/Pkcs11Interop.NetStandard/Pkcs11Interop.DotNetCore.Tests/Pkcs11Interop.DotNetCore.Tests.csproj
src/Pkcs11Interop.NetStandard/Pkcs11Interop/Pkcs11Interop.csproj
src/Pkcs11Interop/Pkcs11InteropTests/Common/_02_CustomExceptionsTest.cs
src/Pkcs11Interop/Pkcs11InteropTests/HighLevelAPI/_28_Pkcs11ClassExtensionTest.cs
src/Pkcs11Interop/Pkcs11InteropTests/Settings.cs

Add support for netstandard20 in 4.x branch

---

src/Pkcs11Interop.Android/Pkcs11Interop.Android.Tests/Pkcs11Interop.Android.Tests.csproj
src/Pkcs11Interop.Android/Pkcs11Interop.Android.Tests/Properties/AndroidManifest.xml
src/Pkcs11Interop.Android/Pkcs11Interop/Pkcs11Interop.csproj
src/Pkcs11Interop/Pkcs11Interop/Common/Platform.cs

Fix platform detection on new Android versions in 4.x branch

---

src/Pkcs11Interop/Common/Platform.cs

Fix platform detection on new Android versions

---

appveyor.yml
build/nuget-sign.bat
src/Pkcs11Interop.Mock/Pkcs11Interop.Mock.csproj
src/Pkcs11Interop.Tests/Common/_02_CustomExceptionsTest.cs
src/Pkcs11Interop.Tests/HighLevelAPI/_28_VendorExtensionsTest.cs
src/Pkcs11Interop.Tests/Pkcs11Interop.Tests.csproj
src/Pkcs11Interop.Tests/Settings.cs
src/Pkcs11Interop/Common/AttributeValueException.cs
src/Pkcs11Interop/Common/LibraryArchitectureException.cs
src/Pkcs11Interop/Common/Pkcs11Exception.cs
src/Pkcs11Interop/Common/Pkcs11UriException.cs
src/Pkcs11Interop/Common/UnmanagedException.cs
src/Pkcs11Interop/Common/UnmanagedLibrary.cs
src/Pkcs11Interop/Common/UnsupportedPlatformException.cs
src/Pkcs11Interop/Pkcs11Interop.csproj

Remove netstandard1.3 target framework

---

src/Pkcs11Interop/Common/UnmanagedException.cs
src/Pkcs11Interop/Common/UnmanagedLibrary.cs

Add error details to UnmanagedException on Windows

---

src/Pkcs11Interop/Common/NativeMethods.cs
src/Pkcs11Interop/Common/UnmanagedLibrary.cs

Alternative implementation for https://github.com/Pkcs11Interop/Pkcs11Interop/pull/140

Use LoadLibraryEx instead of LoadLibrary

---

src/Pkcs11Interop/Common/UnmanagedMemory.cs
src/Pkcs11Interop/HighLevelAPI/MiscSettings.cs
src/Pkcs11Interop/HighLevelAPI40/ObjectAttribute.cs
src/Pkcs11Interop/HighLevelAPI40/Session.cs
src/Pkcs11Interop/HighLevelAPI41/ObjectAttribute.cs
src/Pkcs11Interop/HighLevelAPI41/Session.cs
src/Pkcs11Interop/HighLevelAPI80/ObjectAttribute.cs
src/Pkcs11Interop/HighLevelAPI80/Session.cs
src/Pkcs11Interop/HighLevelAPI81/ObjectAttribute.cs
src/Pkcs11Interop/HighLevelAPI81/Session.cs
src/Pkcs11Interop/ISSUES.txt

Fix reading of array attributes in HighLevelAPI

---

src/Pkcs11Interop/HighLevelAPI40/ObjectAttribute.cs
src/Pkcs11Interop/HighLevelAPI40/Session.cs
src/Pkcs11Interop/HighLevelAPI41/ObjectAttribute.cs
src/Pkcs11Interop/HighLevelAPI41/Session.cs
src/Pkcs11Interop/HighLevelAPI80/ObjectAttribute.cs
src/Pkcs11Interop/HighLevelAPI80/Session.cs
src/Pkcs11Interop/HighLevelAPI81/ObjectAttribute.cs
src/Pkcs11Interop/HighLevelAPI81/Session.cs

Fix processing of unextractable array attributes

---

CONTRIBUTING.md
README.md

Update mailing list info

---

src/Pkcs11Interop/HighLevelAPI40/Session.cs
src/Pkcs11Interop/HighLevelAPI41/Session.cs
src/Pkcs11Interop/HighLevelAPI80/Session.cs
src/Pkcs11Interop/HighLevelAPI81/Session.cs

Enlarge the buffer for C_*EncryptUpdate and C_Decrypt*Update when needed

---

appveyor.yml

Use Appveyor.TestLogger in master

---

appveyor.yml

Let's fix AppVeyor again

---

appveyor.yml
build/nuget-build.bat
src/Pkcs11Interop.Mock/Pkcs11Interop.Mock.csproj
src/Pkcs11Interop.Tests/Pkcs11Interop.Tests.csproj
src/Pkcs11Interop/Pkcs11Interop.csproj

Support for Visual Studio 2022

---

src/Pkcs11Interop.Tests/Common/_01_Pkcs11UriAndBuilderTest.cs
src/Pkcs11Interop.Tests/LowLevelAPI40/_50_MiscellaneousTests.cs
src/Pkcs11Interop.Tests/LowLevelAPI41/_50_MiscellaneousTests.cs
src/Pkcs11Interop.Tests/LowLevelAPI80/_50_MiscellaneousTests.cs
src/Pkcs11Interop.Tests/LowLevelAPI81/_50_MiscellaneousTests.cs
src/Pkcs11Interop/Common/Pkcs11Uri.cs
src/Pkcs11Interop/Common/Pkcs11UriBuilder.cs
src/Pkcs11Interop/LowLevelAPI40/CK_VERSION.cs
src/Pkcs11Interop/LowLevelAPI41/CK_VERSION.cs
src/Pkcs11Interop/LowLevelAPI80/CK_VERSION.cs
src/Pkcs11Interop/LowLevelAPI81/CK_VERSION.cs

Fix handling of Minor part of CK_VERSION structure

---

src/Pkcs11Interop/Common/CKA.cs

Added CKA_NAME_HASH_ALGORITHM

---

appveyor.yml
doc/GETTING_STARTED.md
src/Pkcs11Interop.Tests/Settings.cs

Document how to use Pkcs11Interop on Linux

---

src/Pkcs11Interop/Common/Platform.cs

Possibility to override automatic platform detection
